<?php

include_once('atrium_quiz.features.inc');

/**
* Implementation of hook_init().
*/
function atrium_quiz_init() {
  drupal_add_css(drupal_get_path('module', 'atrium_quiz') .'/atrium_quiz.css');
}

/**
 * Implementation of hook_menu().
 */
function atrium_quiz_menu() {
  $items = array();
  $items['quiz'] = array(
    'title' => 'Quizzes',
    'page callback' => 'atrium_quiz_recent',
    'page arguments' => array(),
    'access arguments' => array('view', 'atrium_quiz'),
    'access callback' => 'spaces_access_feature',
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'features',
  );
  
  return $items;
}

function atrium_quiz_recent() {
  return views_embed_view('lc_latest_quizzes', 'page_1');
}


/**
 * Implementation of hook_menu_alter().
 */
function atrium_quiz_menu_alter(&$items) {
  // Remove shoutbox node add page.
  if (isset($items['node/add/long-answer'])) {
    unset($items['node/add/long-answer']);
  }
  if (isset($items['node/add/matching'])) {
    unset($items['node/add/matching']);
  }    
  if (isset($items['node/add/multichoice'])) {
    unset($items['node/add/multichoice']);
  } 
  if (isset($items['node/add/quiz-directions'])) {
    unset($items['node/add/quiz-directions']);
  } 
  if (isset($items['node/add/short-answer'])) {
    unset($items['node/add/short-answer']);
  } 
  if (isset($items['node/add/truefalse'])) {
    unset($items['node/add/truefalse']);
  } 
}



// Hook into views and restrict access by views to the workflows
function atrium_quiz_views_query_alter(&$view, &$query) {
  if ($view->name == "lc_latest_quizzes" && $space = spaces_get_space()) {
    $where = array(
      'clauses' => array(
        'node_revisions_quiz_node_properties__node.nid IN (SELECT nid FROM og_ancestry WHERE group_nid = %d)',
      ),
      'args' => array(
        $space->id,
      ),
      'type' => 'AND',
    );
    $query->where = array($where);
  }
}


// alter view to add where clause to eliminate if nid not in group... cludgy, file issue?
// permissions + add to og + other variables?
